# Generated by Django 4.2.3 on 2023-08-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
